{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chaquo.python.runtime",
    "module": "chaquopy_java",
    "version": "15.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.1.jar",
          "url": "chaquopy_java-15.0.1.jar",
          "size": 34269,
          "sha512": "df811ae2b6cdbdeb234eba68dfe6f5c4965df577a341a751dcc23414822e32331ed75fc48aedc589283ea9dbcfc83bee0acf799fca86ce039f58449ce872b412",
          "sha256": "552a75c0a36e880119d07a2a2cc3aefb87fb68481734bf40f102a9ed8aae9977",
          "sha1": "b910dae59f05af92ab609843a63767e47f8a0d86",
          "md5": "318044a7ca67fffc55d77787606eeff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations-java5",
          "version": {
            "requires": "15.0"
          }
        }
      ],
      "files": [
        {
          "name": "chaquopy_java-15.0.1.jar",
          "url": "chaquopy_java-15.0.1.jar",
          "size": 34269,
          "sha512": "df811ae2b6cdbdeb234eba68dfe6f5c4965df577a341a751dcc23414822e32331ed75fc48aedc589283ea9dbcfc83bee0acf799fca86ce039f58449ce872b412",
          "sha256": "552a75c0a36e880119d07a2a2cc3aefb87fb68481734bf40f102a9ed8aae9977",
          "sha1": "b910dae59f05af92ab609843a63767e47f8a0d86",
          "md5": "318044a7ca67fffc55d77787606eeff8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.1-javadoc.jar",
          "url": "chaquopy_java-15.0.1-javadoc.jar",
          "size": 321474,
          "sha512": "fc53c43445db787d08e682e90cff83f6f06a7b9239b51c2463b1800fe95d049c07e726aab19cb1957aed9fcadc034f11962d4854fcf54c6bc68b754fb19916a9",
          "sha256": "119915e822200b8fbbcb07f973b02c4e8fd2ba6ad1fab01d72d7e115c340bf05",
          "sha1": "410a266de32de0462a0fd7ac29bb3052880120cd",
          "md5": "fba553036e220b113d539656e19e682e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.1-sources.jar",
          "url": "chaquopy_java-15.0.1-sources.jar",
          "size": 23298,
          "sha512": "cf21538aeed47b3e813638aadcf4f297a61162d76ca8992d9c242f9d8ebcf6876f062604b0034d51867b34268feb024c7c0469c7f0b08e13524814da809b318a",
          "sha256": "85288461b71891b39e854518ca32df0fd1fac88e117f23ef80ee9f4f47a475a8",
          "sha1": "025c1e69ae661b9df331daeecf28827633229181",
          "md5": "66c30b7afec583a4ef2115a48c6219ff"
        }
      ]
    }
  ]
}
