{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chaquo.python",
    "module": "gradle",
    "version": "15.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-15.0.1.jar",
          "url": "gradle-15.0.1.jar",
          "size": 2406793,
          "sha512": "6659949f3d61cad91013c4c173aaa8003643698ed7ad9a9593731ee7f00d6e16131bdb57e12435144bc1ae94dc1e672e0e862a9916bb85ad459d8258fc6345af",
          "sha256": "8ef6b9e2b699aa989258889d73f6572d69d268b5fae71ebe1cda96d277f14ff8",
          "sha1": "94b6c5bf40b2ece0f3db8823634ef9956ac287ae",
          "md5": "49d639c68bbb891e10542f810534c825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20160810"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-15.0.1.jar",
          "url": "gradle-15.0.1.jar",
          "size": 2406793,
          "sha512": "6659949f3d61cad91013c4c173aaa8003643698ed7ad9a9593731ee7f00d6e16131bdb57e12435144bc1ae94dc1e672e0e862a9916bb85ad459d8258fc6345af",
          "sha256": "8ef6b9e2b699aa989258889d73f6572d69d268b5fae71ebe1cda96d277f14ff8",
          "sha1": "94b6c5bf40b2ece0f3db8823634ef9956ac287ae",
          "md5": "49d639c68bbb891e10542f810534c825"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-15.0.1-javadoc.jar",
          "url": "gradle-15.0.1-javadoc.jar",
          "size": 284005,
          "sha512": "179f740b2d51fa38619af4deda1af90c997d207de986ae51e56f4ad7fd0de5645b18a6f76df8dd9b7ff692c05c592bcf973937b387b29ba7306f61c5019df970",
          "sha256": "42fdf4609509cbd53b362f60f3822512193f99805170306dc0f4e65ad958e676",
          "sha1": "baad6f40b4b8c06efff4ec6e85e6cb34896fb760",
          "md5": "399f1757ee43d509ee81c457d2b25188"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-15.0.1-sources.jar",
          "url": "gradle-15.0.1-sources.jar",
          "size": 167527,
          "sha512": "0c0260c56961d2585354a2e238d9b0a582d24465938023d518886178246dfc35c9a94dbc7d25544756cb71c8ca3678a3a3f6637d6a378de6e408173bb0e9d168",
          "sha256": "40022c0bd6c7f31649106535afcf19edb7e94cfae1f10db29b6094640deddb2b",
          "sha1": "a97054939a32837dd2dad177c0db8e05971d4e4a",
          "md5": "77827a63d9ea4c31de13add40cdd59b0"
        }
      ]
    }
  ]
}
