{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chaquo.python.runtime",
    "module": "chaquopy_java",
    "version": "15.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.0.jar",
          "url": "chaquopy_java-15.0.0.jar",
          "size": 32902,
          "sha512": "2a28fd9977a6c0b503513196ac2d360a89ed2eb4a26f1cc4dab8985c135bced8f7c12f5c9a7b5f8c38c13057434321c1beaf222b2ce7ae0d5c94cd851e60890c",
          "sha256": "ef8cd5f188f1453676f8e0644334d6e8ec5c49c5f131075f9afb033651bad45b",
          "sha1": "cb8632baa34a5c6a9a968718540f2a4eb158a693",
          "md5": "2838dcaa1c0afe9c9f0c89a98690884d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations-java5",
          "version": {
            "requires": "15.0"
          }
        }
      ],
      "files": [
        {
          "name": "chaquopy_java-15.0.0.jar",
          "url": "chaquopy_java-15.0.0.jar",
          "size": 32902,
          "sha512": "2a28fd9977a6c0b503513196ac2d360a89ed2eb4a26f1cc4dab8985c135bced8f7c12f5c9a7b5f8c38c13057434321c1beaf222b2ce7ae0d5c94cd851e60890c",
          "sha256": "ef8cd5f188f1453676f8e0644334d6e8ec5c49c5f131075f9afb033651bad45b",
          "sha1": "cb8632baa34a5c6a9a968718540f2a4eb158a693",
          "md5": "2838dcaa1c0afe9c9f0c89a98690884d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.0-javadoc.jar",
          "url": "chaquopy_java-15.0.0-javadoc.jar",
          "size": 322144,
          "sha512": "05f6a4c21c014675119ae9e1e817790e9b6f3e2aea341e8fb29a259d5780139360267a1ff1b8e71899d0589d03ef5b2c42bbfd59b8717095eeb18ba2c6fa5c46",
          "sha256": "1050ac2ff327a9e88a991b0f791d9defb16e7ea0b883f88c36d46c76580b8878",
          "sha1": "9e1296c7a0943f92be774b5cfe4f16d750a31d61",
          "md5": "91e6e47311f8b54ef10e57eafe198dab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chaquopy_java-15.0.0-sources.jar",
          "url": "chaquopy_java-15.0.0-sources.jar",
          "size": 22386,
          "sha512": "e669623b298e134f43b8cc8842fbe0c932cbda5accdb482626439bf149a4fea0aa7558d576593b9de33d6866b1c859e062c4988d99b9e83490b65dd740d8ccb4",
          "sha256": "9edd282eda63daa71d65aa84ab6c1e21e97aeb2277f4868fb1c66855f0725d10",
          "sha1": "bd7759191a783debbd7d4360902a714db849412e",
          "md5": "484c4e24089a45c935d4c96d25928f03"
        }
      ]
    }
  ]
}
